Repository ember-cli/ember-cli-htmlbars, pull requests merged in 2019-10, with the labels that each got.

#318 Ensure all debug logging is emitted with `DEBUG=ember-cli-htmlbars:*`
  lib/ember-addon-main.js
  lib/utils.js
Labels: documentation

#322 Fix issue with deduplcation of babel plugin when parallelized
  lib/ember-addon-main.js
  lib/utils.js
  node-tests/utils_test.js
Labels: bug

#323 Ensure deprecation message shows correct heirarchy.
  lib/ember-addon-main.js
Labels: documentation

#324 More fixes for proper babel plugin deduplication.
  lib/ember-addon-main.js
  lib/utils.js
  node-tests/utils_test.js
Labels: bug

#125 Add more tests using AST plugins (inline and standalone)
  tests/dummy/app/templates/components/x-module-name-inlined-component.hbs
  tests/dummy/app/templates/components/x-module-name-reversed-component.hbs
  tests/dummy/lib/module-name-inliner/index.js
  tests/integration/components/ast-plugins-test.js
  tests/integration/components/test-inline-precompile-test.js
Labels: internal

#332 Ensure "pods style" templates are compiled properly.
  lib/colocated-broccoli-plugin.js
  node-tests/colocated-plugin-test.js
Labels: bug

#333 Enable colocated component classes to be TypeScript
  lib/colocated-broccoli-plugin.js
  node-tests/colocated-plugin-test.js
Labels: bug

#334 Add parent's name to logging output.
  lib/ember-addon-main.js
Labels: enhancement

#336 Support `as default` exports with template colocation
  lib/colocated-babel-plugin.js
  node-tests/babel-plugin-test.js
  package.json
  yarn.lock
Labels: bug

#338 Add broccoli plugin + babel plugin colocation tests
  node-tests/colocated-babel-plugin-test.js
  node-tests/colocated-broccoli-plugin-test.js
  node-tests/colocated-test.js
  package.json
  yarn.lock
Labels: internal

#340 Fix issues when using colocated component's with decorators.
  lib/colocated-babel-plugin.js
  node-tests/colocated-babel-plugin-test.js
  package.json
  yarn.lock
Labels: bug

#341 Add test using native classes + decorators.
  .eslintrc.js
  package.json
  tests/colocation/app/components/its-native.hbs
  tests/colocation/app/components/its-native.js
  tests/integration/components/colocation-test.js
  yarn.lock
Labels: internal

#342 Add `ember-octane` test suite run to CI.
  .github/workflows/ci.yml
Labels: internal
