Repository ember-cli/ember-cli-htmlbars, pull requests merged in 2021-02, with the labels that each got.

#657 Make cacheKey lazy
  lib/utils.js
Labels: enhancement

#659 Enable experimentation via `ember-template-imports` addon
  ember-cli-build.js
  lib/ember-addon-main.js
  lib/utils.js
  node-tests/addon-test.js
  package.json
  tests/integration/components/test-inline-precompile-test.js
  yarn.lock
Labels: internal

#660 Replace `purgeModule` cache busting with `vm` based sandboxing
  lib/utils.js
  node-tests/purge-module-test.js
Labels: enhancement

#662 Avoid building the template compiler cache key repeatedly
  lib/template-compiler-plugin.js
  lib/utils.js
  node-tests/addon-test.js
  node-tests/ast_plugins_test.js
  node-tests/template_compiler_test.js
Labels: bug

#661 Remove usage of registerPlugin / unregisterPlugin
  lib/template-compiler-plugin.js
  lib/utils.js
  node-tests/ast_plugins_test.js
  node-tests/template_compiler_test.js
Labels: enhancement

#663 Ember Ember 3.27+ can determine global for template compilation
  .github/workflows/ci.yml
  lib/utils.js
Labels: bug

#665 Ensure AST plugins have the same ordering as < ember-cli-htmlbars@5.5.0.
  lib/template-compiler-plugin.js
  lib/utils.js
Labels: bug
